### ISSUE TITLE
particle class

### ISSUE THREAD

**Issue by annesbl** [annesbl/daais_particles#2]
deciding which parameters should be in the parent class, particle, and which ones in the child class.

PARENT:
- add methods for individual particle movement based on interactions
- implement method to handle random noise in particle movement
- functionality to serialize particle data for saving or loading simulations

CHILD:
- implement method to initialize multiple particles with random or defined attributes
- function to update all particles in one simulation step
- visualize all particles on the board (create connection to visualisation engine)

DONNT FORGET UNIT TESTS!!

**Comment by amilin23** [comment]
deciding which parameters should be in the parent class, particle, and which ones in the child class.

PARENT CLASS : Particle 

PROPERTIES
1. position: A list [x, y] representing the current position of the particle.
2. velocity: A list [vx, vy] representing the current velocity of the particle.
3. particle_type: A string indicating the particle's type (e.g., "A", "B").

METHODS
1. move(self, boundary):
Handles individual particle movement based on its velocity.
Ensures the particle stays within the defined boundaries, applying reflections if necessary.

2. apply_noise(self, noise_strength):
Introduces random noise to the particle's velocity, simulating chaotic or stochastic behavior.

3. serialize(self):
Converts the particle’s data (position, velocity, particle_type) into a dictionary format for saving or exporting.

4. deserialize(cls, data):
Reconstructs a particle object from serialized data.


CHILD CLASS : ParticleSystem 

PROPERTIES 
1. particles: A list of Particle objects managed by the system.
2. boundary: A tuple (width, height) representing the simulation area size.

METHODS 
1. initialize_particles(self, count, boundary, types):
Creates multiple Particle objects with random or predefined positions, velocities, and types.
Returns a list of particles.

2. update(self, noise_strength=0.1):
Updates all particles for one simulation step:
Applies random noise.
Moves each particle based on its velocity and interactions.

3. serialize_particles(self):
Serializes the data for all particles in the system into a list of dictionaries.

4. visualize(self, visualizer):
Sends particle data to a visualization engine to render them on the screen.

**Comment by amilin23** [comment]
UNIT TEST 
Class: TestParticle

Methods
1. test_particle_initialization:
Tests whether a Particle object is correctly initialized with given position, velocity, and type.

2. test_particle_move_within_boundary:
Tests if the move method updates the particle's position correctly when it moves within the simulation boundaries.

3. test_particle_move_outside_boundary:
Tests if the move method correctly handles boundary collisions by reflecting the velocity.

4. test_apply_noise:
Tests if random noise is correctly added to the particle's velocity.

5. test_serialize_and_deserialize:
Tests if the serialize and deserialize methods correctly save and restore a particle's state.


Class: TestParticleSystem

Methods

1. test_initialize_particles:
Tests if the ParticleSystem correctly initializes the specified number of particles with random positions, velocities, and types.

2. test_update:
Tests if the update method correctly moves all particles and applies noise to their velocities.

3. test_serialize_particles:
Tests if the serialize_particles method correctly converts all particles into dictionaries for saving.
