### ISSUE TITLE
which GUI

### ISSUE THREAD

**Issue by annesbl** [annesbl/daais_particles#4]
someone has to have a closer look into the different GUIs.
DearPy Gui
PyGame
VisPy

**Comment by julnas** [comment]
### Pygame – Einführung und Anwendung
Pygame ist eine beliebte Python-Bibliothek, die ursprünglich für die Entwicklung von 2D-Spielen entwickelt wurde. Sie eignet sich jedoch auch hervorragend für Echtzeit-Visualisierungen, einfache GUIs und dynamische Simulationen wie Partikelsysteme.

**Key Features von Pygame**
- Echtzeit-Rendering
- Ermöglicht die Darstellung von Animationen und Simulationen mit hoher Framerate.
- Einfache Event-Handling-Mechanismen
- Unterstützt Benutzerinteraktionen wie Mausklicks, Tasteneingaben und mehr 
- Flexibilität
- Ermöglicht die Kombination von Simulationen mit GUI-Elementen und Soundeffekten.
- Zugänglichkeit
- Leicht zu erlernen, mit einer Vielzahl von Tutorials und Beispielen.
- Kollisionsmechanismen
- Ideal für Simulationen, bei denen Objekte interagieren oder kollidieren sollen.
- Installation

**Pygame kann einfach über pip installiert werden:**
```python
pip install pygame
``` 

**Beispiel für ein Partikelsystem mit Pygame**

_Ein einfaches Beispiel zur Simulation von Partikeln, die sich bewegen und kollidieren:_
```python
import pygame
import random
import sys

# Initialisierung von Pygame
pygame.init()

# Fenstergröße und Farben
WIDTH, HEIGHT = 800, 600
BACKGROUND_COLOR = (0, 0, 0)
PARTICLE_COLOR = (255, 165, 0)

# Fenster erstellen
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Particle Simulation")

# Partikeleigenschaften
NUM_PARTICLES = 100
particles = []

for _ in range(NUM_PARTICLES):
    x = random.randint(0, WIDTH)
    y = random.randint(0, HEIGHT)
    dx = random.uniform(-2, 2)
    dy = random.uniform(-2, 2)
    particles.append({"pos": [x, y], "vel": [dx, dy]})

# Hauptschleife
clock = pygame.time.Clock()

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    # Bildschirm leeren
    screen.fill(BACKGROUND_COLOR)

    # Partikelbewegung
    for particle in particles:
        # Bewegung berechnen
        particle["pos"][0] += particle["vel"][0]
        particle["pos"][1] += particle["vel"][1]

        # Ränder berücksichtigen (Bounce-Effekt)
        if particle["pos"][0] <= 0 or particle["pos"][0] >= WIDTH:
            particle["vel"][0] *= -1
        if particle["pos"][1] <= 0 or particle["pos"][1] >= HEIGHT:
            particle["vel"][1] *= -1

        # Zeichnen der Partikel
        pygame.draw.circle(screen, PARTICLE_COLOR, (int(particle["pos"][0]), int(particle["pos"][1])), 5)

    # Bildschirm aktualisieren
    pygame.display.flip()

    # Framerate
    clock.tick(60)

``` 


### Stärken und Schwächen von Pygame
**Stärken**

Einfache Handhabung: Perfekt für Einsteiger, die interaktive Simulationen oder Spiele erstellen möchten.
Gut dokumentiert: Es gibt viele Tutorials, Beispiele und Community-Support.
Echtzeit-Fähigkeit: Gut geeignet für Simulationen mit mehreren beweglichen Objekten.
Kombination mit Sound und GUI: Ermöglicht es, Simulationen mit Soundeffekten und interaktiven Elementen anzureichern.

**Schwächen**

- Performance-Limits: Für sehr große Datenmengen oder anspruchsvolle Simulationen (z. B. > 10.000 Partikel) weniger geeignet als OpenGL-basierte Bibliotheken wie VisPy.
- Keine nativen 3D-Features: Unterstützt nur 2D-Grafiken, komplexere 3D-Simulationen erfordern Workarounds.
- Manuelle Optimierung notwendig: Bei Simulationen mit vielen Objekten wird die Performance stark durch den Python-Interpreter begrenzt.
### Wann Pygame die richtige Wahl ist
- Für einfache Simulationen: Wenn deine Simulation weniger als 1.000 Partikel umfasst oder nur grundlegende Interaktionen erfordert.
- Für interaktive Visualisierungen: Ideal, wenn Benutzer mit der Simulation interagieren sollen (z. B. durch Mausklicks).
- Für Projekte mit GUI-Elementen: Pygame erlaubt es, Visualisierung und Benutzersteuerung einfach zu kombinieren.
- Falls du Unterstützung bei der Anpassung des Codes oder eine Erweiterung (z. B. Hinzufügen von Benutzerinteraktionen oder spezifischen Simulationseffekten) benötigst, lass es mich wissen!
